resolver: lts-12.17
packages:
- .
- location:
    git: https://github.com/llvm-hs/llvm-hs.git
    commit: llvm-7
  subdirs:
  - llvm-hs
extra-deps:
- llvm-hs-7.0.1
- llvm-hs-pure-7.0.0
flags:
  llvm-hs:
    shared-llvm: false
