resolver: lts-8.19
packages:
- location: .
- location:
    git: https://github.com/llvm-hs/llvm-hs.git
    commit: llvm-4
  subdirs:
  - llvm-hs
extra-deps:
- llvm-hs-4.2.0
- llvm-hs-pure-4.1.0.0
flags:
  llvm-hs:
    shared-llvm: false
